[project]
name = "cours-dq"
version = "1.0.0"
description = "Projet dbt pour le cours Data Quality à CentraleSupélec"
requires-python = ">=3.10"
dependencies = ["dbt-core", "dbt-duckdb", "duckdb", "duckdb-engine"]

[dependency-groups]
dev = []
