version: 2

sources:
  - name: birth_data
    tables:
      - name: departements
        config:
          external_location: "read_csv('data/departements.csv')"
          formatter: oldstyle
        description: "Reference table for departments"
        columns:
          - name: CODE
            description: "Department code (ex. 22, 977...)"
            data_tests:
              - unique
          - name: NOM
            description: "Department name (ex. Côtes-d'Armor, Saint-Barthélemy...)"
            data_tests:
              - not_null
      - name: birth_data_2021
        config:
          external_location: "read_csv('data/donnees_naissances_2021.csv', types={'DEPDOM': 'VARCHAR'})"
          formatter: oldstyle
        description: "Official French birth data for the year 2021"
        columns:
          - name: ANAIS
            description: "Birth year"
            data_tests:
              - not_null
          # TODO: add tests for other columns of the table

          # ex 1: add ID uniqueness test

          # ex 2: add range tests for the age columns (see data dictionary for accepted values)

          # ex 3: add data type tests for the year columns 
          
          # ex 4: verify that all departments in DEPDOM and DEPNAIS are in the departements table

# Bonus: based on the results of the tests, create a new model containing only correct data and run the same tests against it (they should all pass)