version: 2

sources:
  - name: birth_data
    tables:
      - name: departements
        config:
          external_location: "read_csv('data/departements.csv')"
          formatter: oldstyle
        description: "Reference table for departments"
        columns:
          - name: CODE
            description: "Department code (ex. 22, 977...)"
            data_tests:
              - unique
          - name: NOM
            description: "Department name (ex. Côtes-d'Armor, Saint-Barthélemy...)"
            data_tests:
              - not_null
      - name: birth_data_2021
        config:
          external_location: "read_csv('data/donnees_naissances_2021.csv', types={'DEPDOM': 'VARCHAR'})"
          formatter: oldstyle
        description: "Official French birth data for the year 2021"
        columns:
          - name: ID
            description: "Identifiant unique"
            data_tests:
              - not_null
              - unique
          - name: ANAIS
            description: "Année de naissance de l'enfant"
            data_tests:
              - not_null
          - name: ACCOUCHR
            description: "Conditions de l'accouchement"
          - name: AGEMERE
            description: "Age de la mère dans l'année de naissance de l'enfant"
            data_tests:
              - value_in_range:
                  min_value: 17
                  max_value: 47
          - name: AGEPERE
            description: "Age du père dans l'année de naissance de l'enfant"
            data_tests:
              - value_in_range:
                  min_value: 17
                  max_value: 47
          - name: AGEXACTM
            description: "Age exact de la mère à la naissance de l'enfant"
            data_tests:
              - value_in_range:
                  min_value: 17
                  max_value: 47
          - name: AGEXACTP
            description: "Age exact du père à la naissance de l'enfant"
            data_tests:
              - value_in_range:
                  min_value: 17
                  max_value: 47
          - name: AMAR
            description: "Année de mariage des parents"
            data_tests:
              - is_integer
          - name: ARECC
            description: "Année de reconnaissance conjointe des parents"
          - name: ARECM
            description: "Année de reconnaissance de la mère"
          - name: ARECP
            description: "Année de reconnaissance du père"
          - name: DEPDOM
            description: "Département de domicile de la mère"
            data_tests:
              - relationships:
                  to: ref('departements')
                  field: CODE
          - name: DEPNAIS
            description: "Département de naissance"
          - name: DMARNAIS
            description: "Comparaison des dates anniversaires de mariage des parents et de naissance de l'enfant"
          - name: DURECEVP
            description: "Durée écoulée depuis l'événement précédent"
          - name: INDLNM
            description: "Indicateur du lieu de naissance de la mère"
          - name: INDLNP
            description: "Indicateur du lieu de naissance du père"
          - name: INDNATM
            description: "Indicateur de nationalité de la mère"
          - name: INDNATP
            description: "Indicateur de nationalité du père"
          - name: JRECC
            description: "Jour de reconnaissance conjointe des parents"
          - name: JRECM
            description: "Jour de reconnaissance de la mère"
          - name: JRECP
            description: "Jour de reconnaissance du père"
          - name: MNAIS
            description: "Mois de naissance de l'enfant"
          - name: MRECC
            description: "Mois de reconnaissance conjointe des parents"
          - name: MRECM
            description: "Mois de reconnaissance de la mère"
          - name: MRECP
            description: "Mois de reconnaissance du père"
          - name: NBENF
            description: "Nombre d'enfants issus de l'accouchement"
          - name: ORIGINOM
            description: "Origine du nom de l'enfant"
          - name: SEXE
            description: "Sexe de l'enfant"
          - name: SITUATMR
            description: "Situation professionnelle de la mère"
          - name: SITUATPR
            description: "Situation professionnelle du père"
          - name: TUCOM
            description: "Tranche de commune du lieu de domicile de la mère"
          - name: TUDOM
            description: "Tranche d'unité urbaine 2017 du lieu de domicile de la mère"

          - name: DEPDOM
            description: "Department of mother's residence"
